if: tag IS blank

language: objective-c
osx_image: xcode10.2
xcode_workspace: YDNYNAB.xcworkspace
xcode_scheme: YDNYNAB

before_install:
  pod repo update master --silent && pod install

addons:
  homebrew:
    packages:
      - jq

jobs:
  include:
    script: ./.travis-build.sh
