language: objective-c
osx_image: xcode10.2
xcode_workspace: YDNYNAB.xcworkspace
xcode_scheme: YDNYNAB

before_install:
  pod repo update master --silent && pod install

addons:
  homebrew:
    packages:
      - libofx
      - jq

script:
  set -o pipefail && xcodebuild -workspace "YDNYNAB.xcworkspace" -scheme "YDNYNAB" clean build | xcpretty

script:
  ./.bundle-and-upload.sh
