language: objective-c
osx_image: xcode10.2
xcode_workspace: YDNYNAB.xcworkspace
xcode_scheme: YDNYNAB

before_install:
  pod repo update master --silent && pod install

addons:
  homebrew:
    packages:
      - libofx
      - jq

jobs:
  include:
    - stage: "Build"
      script: set -o pipefail && xcodebuild -workspace "YDNYNAB.xcworkspace" -scheme "YDNYNAB" clean build | xcpretty

    - stage: "Release if needed"
      script: ./.bundle-and-upload.sh
